<h1>{#I-26#}</h1>

<form action="{#url#}" method="post" onsubmit="return checkForm(this)">
<input type="hidden" name="step" value="db" />


<div class="input"><p>{#I-29#}</p>
<input size="50" class="text" type="text" name="email" value="{#url#}" />
</div>

<div class="input"><p>{#I-27#}</p>
<input size="50" class="text" type="text" name="username" value="{#username#}" />
</div>

<div class="input"><p>{#I-28#}</p>
<input size="50" class="text" type="password" name="password" value="" />
</div>


<!-- begin buttons -->
<div class="input">
	<input class="button" type="submit" value="{#I-03#}" />
</div>
<!-- end buttons -->
</form>
<script type="text/javascript">
  function checkForm(form){
   var username=form.username.value;
   var password=form.password.value;
   var email=form.email.value;
   var errors=[];
   if (email==""){
   errors.push("Please enter an email id.")
   }
   if (username==""){
   errors.push("Please enter an username.")
   }
   if (password==""){
   errors.push("Please enter a password.")
   }
   
   var str="";
   if(errors.length > 0){
   var count=errors.length;
   for(var i=0;i<count;i++){
     str +=errors[i] + "\n";
	}
	alert(str);
	return false;
}
return true;
}
</script>
	
   
   
   