<h1>{#I-17#}</h1>

<form action="{#url#}" method="post">
<input type="hidden" name="step" value="finish" />


<div class="input"><p>{#I-30#}</p>
<input size="50" class="text" type="text" name="app_title" value="{#app_title#}" />
</div>

<div class="input"><p>{#I-18#}</p>
<input size="50" class="text" type="text" name="source_root_path" value="{#source_root_path#}" />
</div>

<div class="input"><p>{#I-19#}</p>
<input size="50" class="text" type="text" name="site_root_path" value="{#site_root_path#}" />
</div>



<!-- begin buttons -->
<div class="input">
	<input class="button" type="submit" value="{#I-25#}" />
</div>
<!-- end buttons -->
</form>