<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="{#direction#}" lang="en-US">

<!-- BEGIN html head -->
<meta http-equiv="Content-Type" content="text/html; charset={#charset#}" />
<title>{#G-01#}</title>
<link rel="stylesheet" type="text/css" href="installer/data/templates/style.css" />

<!--RTL-->
</head>
<!-- END html head -->

<body>

<!-- BEGIN wrapper -->
<div id="wrapper"><div class="buffer">

	<!-- BEGIN header -->
	<div id="header">

		
	
	</div>
	<!-- END header -->
	
	<!-- BEGIN body -->
	<div id="body">
	
	<!-- BEGIN content -->
	<div id="content">
	
	{#DATA#}
		
	</div>
	<!-- END content -->
	
	<!-- BEGIN sidebar -->
	<div id="sidebar">
	
		<!-- begin SAMPLE sidebar menu -->
		<h2>{#G-02#}</h2>
		<ul>
		<li {#LINK1#}>{#G-03#}</li>
		<li {#LINK2#}>{#G-07#}</li>
		<li {#LINK3#}>{#G-04#}</li>
		<li {#LINK5#}>{#G-05#}</li>
		<li {#LINK4#}>{#G-06#}</li>
		
		</ul>
		<!-- end SAMPLE sidebar menu -->
	
	</div>
	<!-- END sidebar -->
	
	<div class="break"></div>
	</div>
	<!-- END body -->

</div></div>
<!-- END wrapper -->

<!-- BEGIN footer -->
<div id="footer">
	<p>{#I-24#}</p>
</div>
<!-- END footer -->

</body>

</html>
